### ISSUE TITLE
How to enable Photon Mono X?

### ISSUE THREAD

**Issue by mperino** [ANYCUBIC-3D/PhotonWorkshop#9]
In preparation for the release of Mono X I would like to use Photon WorkShop.  I see videos where it is working in Photon Workshop, but I do not see the option in the latest builds.

How do I enable support for it?

**Comment by mperino** [comment]
Hello @ANYCUBIC-3D & @punliu, 
It's been 27 days since I opened this Issue, with no response.  Hopefully you all had a nice Golden Week, and can answer soon.
I'm trying to update tools to work with Photon Mono X.  To do that I need to get Photon Workshop outputting some 4K files.  There is no option in Configure->Machine Type for "Photon Mono X", and the Resolution setting under Machine Settings is hardlocked.

V2.1.21.RC6 has fixes listed for 4K, but I see no way to enable 4K.

Hopefully you respond soon and I can have the sl1tophoton tool working by the time I get my Mono X.

**Comment by lastowl** [comment]
V2.1.23 ships with the printers and has support for all the new printers

**Comment by mperino** [comment]
Can you post (or email) a link to it?  The latest release on github is V2.2.21, and the same on the anycubic site.

**Comment by lastowl** [comment]
Not my link but from reddit (Windows) https://drive.google.com/file/d/12YNF_7KfwSULl9JAFw_CF9DU0eGeciA0/view?usp=sharing

**Comment by mperino** [comment]
Thank you @lastowl that solves the problem.  Now back to modifing sl1tophoton for the Mono X!
